language: c

sudo: false

services:
    - docker

cache:
  directories:
    - ~/.ghc
    - ~/.cabal

matrix:
  include:
    - env: CABALVER=1.24 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3,zsh],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,zsh], sources: [hvr-ghc]}}
    - env: CABALVER=2.0 GHCVER=8.2.2
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.2,zsh], sources: [hvr-ghc]}}
    - env: CABALVER=2.2 GHCVER=8.4.4
      addons: {apt: {packages: [cabal-install-2.2,ghc-8.4.4,zsh], sources: [hvr-ghc]}}
    - env: CABALVER=2.4 GHCVER=8.6.5
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.6.5,zsh], sources: [hvr-ghc]}}
    - env: CABALVER=2.4.0.0 GHCVER=8.6.5
      os: osx

before_install: |
  if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH; fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    # Set up ghcup
    ( mkdir -p ~/.ghcup/bin && curl https://gitlab.haskell.org/haskell/ghcup/raw/master/ghcup > ~/.ghcup/bin/ghcup && chmod +x ~/.ghcup/bin/ghcup) && echo "Success"
    export PATH="$HOME/.cabal/bin:$HOME/.ghcup/bin:$PATH"
    # Install cabal and ghc
    ghcup install $GHCVER
    ghcup install-cabal $CABALVER
    ghcup set $GHCVER
  fi

install:
 - zsh --version
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests -v2 -f dev
 - cabal build
 - cabal test --show-details=always
 - cabal sdist
 - cabal haddock | grep "100%" | wc -l | grep "4"
 # There is a single Docker image, there are no variants for different versions of GHC
 - if [[ "$GHCVER" == "8.0.2" ]]; then docker build . -t hapistrano; docker run --rm hapistrano --version; fi

notifications:
  email: false
